template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "east2328"
__REPO__ = "lang-mhr"
__UND2C__ = "mhr"
__UNDEFINED__ = "Eastern Mari"
__UND__ = "mhr"
